version: "3"
services:
  jupyterlab-docker:
    container_name: jupyterlab-docker
#    build:
#      context: ./jupyterlab
#      dockerfile: Dockerfile
    image: nuevocs/docker-jupyter-gpu:latest
    restart: always
    entrypoint: >
      jupyter-lab
      --NotebookApp.allow_origin='https://colab.research.google.com'
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
      --NotebookApp.port_retries=0
    ports:
      - ${PORT}:8888
    volumes:
      - ${PWD}/jupyterlab/config:/root/.jupyter
      - ${PWD}/jupyterlab/workspace:/workspace
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
